# Generated by Django 4.2.7 on 2023-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("digital", models.BooleanField(default=False)),
                ("transaction_id", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
